### ISSUE TITLE
Doesn't work anymore due to change on Okta login page

### ISSUE THREAD

**Issue by vladistan** [nimbusscale/okta_aws_login#13]
This script broke this morning after entering user name and password I get the following error message.  Perhaps it's related to Okta recently changing their login page

Traceback (most recent call last):
  File "okta_aws_login.py", line 533, in <module>
    main()
  File "okta_aws_login.py", line 475, in main
    conf_dict['idp_entry_url'])
  File "okta_aws_login.py", line 268, in okta_password_login
    action=action)
UnboundLocalError: local variable 'action' referenced before assignment

**Comment by samuel-72** [comment]
Apparently this does not work anymore. 

```
# Line 262
    for inputtag in formsoup.find_all(re.compile('(FORM|form)')):
        action = inputtag.get('action')

```

**Comment by dgc-wh** [comment]
I started on a fix for this but ran out of time. not sure why this script didn't used the authentication api to begin with

**Comment by etendards** [comment]
Is this app going to be supported going forward?  Has anyone found a Script that works with the new Okta and App level MFA?  I like how this one would renew the sessions.

**Comment by vladistan** [comment]
If you get the latest version of this script for here... it works.  But it still screen scrapes.   So we are at the mercy of Okta to not change their login pages.

Don't know anything about MFA
