### ISSUE TITLE
recieving unboundlocalerror

### ISSUE THREAD

**Issue by jbruettcva** [nimbusscale/okta_aws_login#6]
```
>python c:\users\jbruett\Desktop\okta_aws_login.py
Username: jbadmin
Password for jbadmin:
Traceback (most recent call last):
  File "c:\users\jbruett\Desktop\okta_aws_login.py", line 522, in <module>
    main()
  File "c:\users\jbruett\Desktop\okta_aws_login.py", line 474, in main
    conf_dict['idp_entry_url'])
  File "c:\users\jbruett\Desktop\okta_aws_login.py", line 267, in okta_password_
login
    action=action)
UnboundLocalError: local variable 'action' referenced before assignment

```
running on: Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by brian-campbell** [comment]
I'm getting this same error.  Any resolution to this one?
